apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: 
  namespace: 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: nginx:latest
